#!/bin/bash

function magic() {
    local installed="$(magic_from "$PWD" | tac)"
    local spells

    for magic in $installed; do
        mapfile -t spells <<< "$(bash "$magic/.spells")"
	echo "$magic/.spells: ${spells[@]}"
    done
}

function magic_from() {
    local dir="$1"
    [[ -z "$dir" ]] && return

    while [[ "$dir" != "/" ]]; do
	[[ -r "$dir/.spells" ]] && echo "$dir "
	dir="$(dirname "$dir")"
    done
}

function magic_install() {
    source "$1/.spells" > /dev/null
}

function magic_uninstall() {
    unset $(bash "$1/.spells")
}

if [[ "$PWD" != "$MAGIC_LAST" ]]; then
    
    uninstall="$(magic_from "$MAGIC_LAST")"
    install="$(magic_from "$PWD" | tac)"

    if [[ "$uninstall" != "$install" ]]; then

	for magic in $uninstall; do
	    magic_uninstall "$magic"
	done
	
	for magic in $install; do
	    magic_install "$magic"
	done
    fi;

    unset install uninstall
    MAGIC_LAST="$PWD"
fi;
